# Generated by Django 6.0.2 on 2026-04-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports_logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("in_warehouse", "In Warehouse"),
                    ("assigned", "Assigned to Courier"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                ],
                default="processing",
                max_length=30,
            ),
        ),
    ]
